spring.application.name=todo
# Tell Hibernate to only check if the table exists, not create it
spring.jpa.hibernate.ddl-auto=validate
# Ensure Liquibase is looking at the right file (usually default, but good to be explicit)
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb